default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: food

#test:
#  <<: *default
#  database: site_with_adm

production:
  adapter: postgresql
  encoding: utf8
  username: innayiqxweiqzv
  password: xF79K8Ox7AbKf6dzm4dGC0PJVn
  host: ec2-54-83-198-159.compute-1.amazonaws.com
  port: 5432
  pool: 5
  timeout: 5000
  database: db3l9u5bdgnh03